import { PageTransition } from "@/components/PageTransition";
import { Link } from "wouter";
import { FileText, ArrowLeft } from "lucide-react";
import { PageSEO, PAGE_SEO } from "@/components/PageSEO";

export default function TermsPage() {
  return (
    <div className="relative min-h-[100dvh] forge-bg-glow">
      <PageSEO {...PAGE_SEO.terms} />
      <main id="main-content" className="relative z-10 mx-auto max-w-3xl px-4 py-10">
        <PageTransition>
          <Link href="/" className="mb-6 inline-flex items-center gap-2 text-xs text-[#4B5563] hover:text-[#A78BFA] transition-colors">
            <ArrowLeft size={13} /> Back to FocusArx
          </Link>

          <header className="mb-8">
            <div className="mb-3 flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[rgba(124,58,237,0.15)]">
                <FileText size={20} className="text-[#A78BFA]" />
              </div>
              <div>
                <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#4B5563]">Legal</p>
                <h1 className="text-2xl font-bold text-[#E2E8F0]">Terms of Service</h1>
              </div>
            </div>
            <p className="text-xs text-[#4B5563]">Last updated: June 2025</p>
          </header>

          <div className="space-y-8">
            <Section title="1. Acceptance of Terms">
              <p>By accessing or using FocusArx, you agree to be bound by these Terms of Service and our <Link href="/privacy" className="text-[#A78BFA] hover:underline">Privacy Policy</Link>. If you do not agree, do not use the service.</p>
            </Section>

            <Section title="2. Description of Service">
              <p>FocusArx is an AI-powered productivity platform offering Pomodoro-style focus tracking, gamification (XP, coins, badges, leaderboards), AI coaching, webcam-based attention monitoring, and study analytics. The service is provided "as is" and may evolve over time.</p>
            </Section>

            <Section title="3. Eligibility">
              <p>You must be at least 13 years old to use FocusArx. By creating an account, you represent that you meet this requirement.</p>
            </Section>

            <Section title="4. User Accounts">
              <ul>
                <li>You are responsible for maintaining the confidentiality of your credentials.</li>
                <li>You must notify us immediately of any unauthorised account access.</li>
                <li>Guest accounts are temporary and data may be purged after 30 days of inactivity.</li>
                <li>One person may not maintain multiple accounts to gain unfair leaderboard advantages.</li>
              </ul>
            </Section>

            <Section title="5. Acceptable Use">
              <p>You agree to use FocusArx only for lawful purposes and in accordance with our <Link href="/acceptable-use" className="text-[#A78BFA] hover:underline">Acceptable Use Policy</Link>. You must not attempt to reverse-engineer, scrape, or otherwise exploit the service.</p>
            </Section>

            <Section title="6. AI-Generated Content">
              <p>AI coaching responses and roadmaps are generated by third-party AI models and are for informational and motivational purposes only. They do not constitute professional advice. See our <Link href="/ai-policy" className="text-[#A78BFA] hover:underline">AI Policy</Link> for details.</p>
            </Section>

            <Section title="7. Intellectual Property">
              <p>FocusArx and its original content, features, and functionality are owned by FocusArx and are protected by applicable intellectual property laws. You retain ownership of any content you create (tasks, notes, goals).</p>
            </Section>

            <Section title="8. Disclaimers & Limitation of Liability">
              <p>FocusArx is provided without warranty of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service. Our maximum liability to you shall not exceed the amount you paid us in the 12 months prior to the claim.</p>
            </Section>

            <Section title="9. Termination">
              <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time via the <Link href="/data-deletion" className="text-[#A78BFA] hover:underline">data deletion page</Link>.</p>
            </Section>

            <Section title="10. Changes to Terms">
              <p>We may update these terms periodically. Continued use of the service after changes constitutes acceptance of the revised terms. We will notify registered users of material changes by email where possible.</p>
            </Section>

            <Section title="11. Governing Law">
              <p>These terms are governed by applicable laws. Any disputes shall be resolved through good-faith negotiation before any formal proceedings.</p>
            </Section>

            <Section title="12. Contact">
              <p>Questions? Email <span className="text-[#A78BFA]">legal@focusarx.app</span></p>
            </Section>
          </div>

          <LegalFooter />
        </PageTransition>
      </main>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="rounded-2xl border border-[rgba(124,58,237,0.1)] bg-[rgba(16,23,50,0.4)] p-6">
      <h2 className="mb-3 text-base font-semibold text-[#E2E8F0]">{title}</h2>
      <div className="space-y-2 text-sm leading-relaxed text-[#94A3B8] [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1">{children}</div>
    </section>
  );
}

function LegalFooter() {
  const links = [
    { href: "/privacy", label: "Privacy" },
    { href: "/terms", label: "Terms" },
    { href: "/cookie-policy", label: "Cookies" },
    { href: "/acceptable-use", label: "Acceptable Use" },
    { href: "/ai-policy", label: "AI Policy" },
    { href: "/data-deletion", label: "Data Deletion" },
  ];
  return (
    <div className="mt-10 flex flex-wrap gap-3 border-t border-[rgba(124,58,237,0.1)] pt-6">
      {links.map(({ href, label }) => (
        <Link key={href} href={href} className="text-xs text-[#4B5563] hover:text-[#A78BFA] transition-colors">
          {label}
        </Link>
      ))}
    </div>
  );
}
