import { PageTransition } from "@/components/PageTransition";
import { Link } from "wouter";
import { FileText, ArrowLeft } from "lucide-react";
import { PageSEO, PAGE_SEO } from "@/components/PageSEO";

export default function TermsPage() {
  return (
    <div className="relative min-h-[100dvh] forge-bg-glow">
      <PageSEO {...PAGE_SEO.terms} />
      <main id="main-content" className="relative z-[var(--z-content)] mx-auto max-w-3xl px-4 py-10">
        <PageTransition>
          <Link href="/" className="mb-6 inline-flex items-center gap-2 text-xs text-[var(--foreground-subtle)] hover:text-[var(--brand-400)] transition-colors">
            <ArrowLeft size={13} /> Back to FocusArx
          </Link>

          <header className="mb-8">
            <div className="mb-3 flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[var(--rgba-124-58-237-0_15)]">
                <FileText size={20} className="text-[var(--brand-400)]" />
              </div>
              <div>
                <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[var(--foreground-subtle)]">Legal</p>
                <h1 className="text-2xl font-bold text-[var(--foreground)]">Terms of Service</h1>
              </div>
            </div>
            <p className="text-xs text-[var(--foreground-subtle)]">Last updated: September 2026</p>
          </header>

          <div className="space-y-8">
            <Section title="1. Acceptance of Terms">
              <p>By accessing or using FocusArx, you agree to be bound by these Terms of Service and our <Link href="/privacy" className="text-[var(--brand-400)] hover:underline">Privacy Policy</Link>. If you do not agree, do not use the service.</p>
            </Section>

            <Section title="2. Description of Service">
              <p>FocusArx is an AI-powered productivity platform offering Pomodoro-style focus tracking, gamification (XP, coins, badges, leaderboards), AI coaching, webcam-based attention monitoring, and study analytics. The service is provided "as is" and may evolve over time.</p>
            </Section>

            <Section title="3. Eligibility">
              <p>You must be at least 13 years old to use FocusArx. By creating an account, you represent that you meet this requirement.</p>
            </Section>

            <Section title="4. User Accounts">
              <ul>
                <li>You are responsible for maintaining the confidentiality of your credentials.</li>
                <li>You must notify us immediately of any unauthorised account access.</li>
                <li>Guest accounts are temporary and data may be purged after 30 days of inactivity.</li>
                <li>One person may not maintain multiple accounts to gain unfair leaderboard advantages.</li>
              </ul>
            </Section>

            <Section title="5. Acceptable Use">
              <p>You agree to use FocusArx only for lawful purposes and in accordance with our <Link href="/acceptable-use" className="text-[var(--brand-400)] hover:underline">Acceptable Use Policy</Link>. You must not attempt to reverse-engineer, scrape, or otherwise exploit the service.</p>
            </Section>

            <Section title="6. AI-Generated Content">
              <p>AI coaching responses and roadmaps are generated by third-party AI models and are for informational and motivational purposes only. They do not constitute professional advice. See our <Link href="/ai-policy" className="text-[var(--brand-400)] hover:underline">AI Policy</Link> for details.</p>
            </Section>

            <Section title="7. Intellectual Property">
              <p>FocusArx and its original content, features, and functionality are owned by FocusArx and are protected by applicable intellectual property laws. You retain ownership of any content you create (tasks, notes, goals).</p>
            </Section>

            <Section title="8. Pro Purchases, Focus Credits & Refunds">
              <p>Pro may be activated through a recurring card/UPI plan or through Focus Credits earned inside the service. Display prices include the billing interval shown at checkout; the payment provider's final checkout screen is authoritative. Focus Credits have no cash value, cannot be transferred or withdrawn, and are not cryptocurrency.</p>
              <p className="mt-3">You can cancel a recurring plan through the applicable payment support flow; access continues through the paid period unless a refund requires earlier revocation. Refund requests are reviewed under applicable consumer law and provider rules. Contact focusarx@gmail.com with the account email and provider payment ID—never send full card or UPI credentials.</p>
            </Section>

            <Section title="9. Disclaimers & Limitation of Liability">
              <p>FocusArx is provided "as is" without warranty of uninterrupted availability. To the extent permitted by law, we are not liable for indirect, incidental, or consequential damages. Nothing in these terms excludes consumer rights or liability that applicable law does not permit us to exclude.</p>
            </Section>

            <Section title="10. Termination">
              <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time via the <Link href="/data-deletion" className="text-[var(--brand-400)] hover:underline">data deletion page</Link>.</p>
            </Section>

            <Section title="11. Changes to Terms">
              <p>We may update these terms periodically. Continued use of the service after changes constitutes acceptance of the revised terms. We will notify registered users of material changes by email where possible.</p>
            </Section>

            <Section title="12. Governing Law">
              <p>These terms are governed by applicable laws. Any disputes shall be resolved through good-faith negotiation before any formal proceedings.</p>
            </Section>

            <Section title="13. Contact">
              <p>Questions? Email <a href="mailto:focusarx@gmail.com" className="text-[var(--brand-400)] hover:underline">focusarx@gmail.com</a> or call <a href="tel:+917725004639" className="text-[var(--brand-400)] hover:underline">+91 77250 04639</a>.</p>
            </Section>
          </div>

          <LegalFooter />
        </PageTransition>
      </main>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="rounded-2xl border border-[var(--rgba-124-58-237-0_1)] bg-[var(--rgba-16-23-50-0_4)] p-6">
      <h2 className="mb-3 text-base font-semibold text-[var(--foreground)]">{title}</h2>
      <div className="space-y-2 text-sm leading-relaxed text-[var(--foreground-muted)] [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1">{children}</div>
    </section>
  );
}

function LegalFooter() {
  const links = [
    { href: "/privacy", label: "Privacy" },
    { href: "/terms", label: "Terms" },
    { href: "/cookie-policy", label: "Cookies" },
    { href: "/acceptable-use", label: "Acceptable Use" },
    { href: "/ai-policy", label: "AI Policy" },
    { href: "/data-deletion", label: "Data Deletion" },
    { href: "/accessibility", label: "Accessibility" },
  ];
  return (
    <div className="mt-10 flex flex-wrap gap-3 border-t border-[var(--rgba-124-58-237-0_1)] pt-6">
      {links.map(({ href, label }) => (
        <Link key={href} href={href} className="text-xs text-[var(--foreground-subtle)] hover:text-[var(--brand-400)] transition-colors">
          {label}
        </Link>
      ))}
    </div>
  );
}
