/**
 * The canonical battle-pass module: season identity, the tier ladder, and the
 * claim bookkeeping helpers.
 *
 * `BATTLE_PASS_TIERS`, `calculateBattlePassTier` and `nextBattlePassThreshold`
 * all derive from one ladder (`requiredXpForTierIndex` in `battlePassSeasons`)
 * — the same one the battle-pass page renders and the admin builder publishes.
 * That matters: when these disagreed, the page offered a Claim button for a
 * tier the claim gate then rejected.
 */
import { MAX_TIERS, buildSeasonTiers, describeReward, requiredXpForTierIndex } from "./battlePassSeasons";
import { currentTierForXp } from "./battlePassTiers";

/**
 * Battle-pass seasons are ISO weeks (Mon–Sun, UTC) — deterministic from the
 * date, so every serverless instance agrees without any coordination or cron.
 * A rollover is a lazy, idempotent per-user reset: the first request after the
 * week boundary (session reward or battle-pass fetch) moves the user to the new
 * season. Unclaimed tiers are forfeited at the boundary.
 */
export function currentBattlePassSeason(now: Date = new Date()): number {
  const d = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  const day = d.getUTCDay() || 7; // ISO: Monday=1..Sunday=7
  d.setUTCDate(d.getUTCDate() + 4 - day); // Thursday of this ISO week
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  const week = Math.ceil(((d.getTime() - yearStart.getTime()) / 86_400_000 + 1) / 7);
  return d.getUTCFullYear() * 100 + week;
}

/** ISO instant of the next Monday 00:00 UTC (season boundary). */
export function battlePassSeasonEndsAt(now: Date = new Date()): Date {
  const d = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  const day = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + (8 - day)); // next Monday
  return d;
}


export type BattlePassReward = {
  type: "coins" | "xp" | "bundle";
  value: number;
  icon: string;
  name: string;
  label: string;
  coins: number;
  xp: number;
};

function reward(coins: number, xp: number, label: string): BattlePassReward {
  const type = coins > 0 && xp > 0 ? "bundle" : coins > 0 ? "coins" : "xp";
  return {
    type,
    value: type === "coins" ? coins : type === "xp" ? xp : coins + xp,
    icon: type === "coins" ? "🪙" : type === "xp" ? "⚡" : "🎁",
    name: label,
    label,
    coins,
    xp,
  };
}

/**
 * The canonical season table, as the legacy display shape the retention and
 * loot-box routes consume (`name`/`label`/`value`/`coins`/`xp`).
 *
 * It used to be a hand-written eight-tier array that stopped at 8,000 XP, while
 * the battle-pass page renders a 30-tier season — so "max tier" meant 8 in one
 * place and 30 in another, and a loot box that skipped tiers could not reach
 * past 8. It is now generated by the same pure function the page and the admin
 * builder use, and mapped into the old shape so every existing consumer keeps
 * working.
 */
export const BATTLE_PASS_TIERS = buildSeasonTiers({ tierCount: MAX_TIERS, seed: "canonical" }).map((tier) => ({
  tier: tier.tier,
  xpRequired: tier.requiredXp,
  freeReward: reward(tier.free.coins ?? 0, tier.free.xp ?? 0, describeReward(tier.free)),
  premiumReward: {
    ...reward(tier.premium.coins ?? 0, 0, describeReward(tier.premium)),
    tokens: tier.premium.tokens ?? 0,
    cosmeticId: tier.premium.cosmeticId,
    lootbox: tier.premium.lootbox,
  },
}));

/**
 * Highest tier any season can reach — the same clamp the admin builder enforces,
 * so a 50-tier authored season is fully progressable rather than truncated at
 * the 30-tier default.
 */
export const BATTLE_PASS_MAX_TIER = MAX_TIERS;

/**
 * Highest tier fully unlocked by `seasonXp`.
 *
 * Delegates to the same ladder as the page, the claim gate and the admin
 * builder. Tier 1 needs 500 XP (one 25-minute session at 20 XP/min), so a
 * brand-new account starts at tier 0 and has something to do on day one.
 */
export function calculateBattlePassTier(seasonXp: number): number {
  // Non-finite input is a bug upstream, not a tier — treat a positive overflow
  // as "top of the season" and anything else as zero rather than throwing.
  if (!Number.isFinite(seasonXp)) return seasonXp > 0 ? BATTLE_PASS_MAX_TIER : 0;
  const safeXp = Math.max(0, Math.floor(seasonXp));
  return currentTierForXp(safeXp, requiredXpForTierIndex, BATTLE_PASS_MAX_TIER);
}

/** XP needed for the tier after `currentTier`, or null once the season is done. */
export function nextBattlePassThreshold(currentTier: number): number | null {
  if (currentTier < 0 || currentTier >= BATTLE_PASS_MAX_TIER) return null;
  return requiredXpForTierIndex(currentTier + 1);
}

/** Premium claim IDs share one integer[] column without colliding with free claims. */
export function battlePassClaimId(tier: number, track: "free" | "premium"): number {
  return track === "premium" ? tier + 100 : tier;
}

/**
 * Lazy, idempotent weekly rollover. Returns true when the user's season was
 * just reset. Unclaimed tiers are forfeited at the boundary; claimed rewards
 * were already paid out.
 */
export async function rolloverBattlePassSeason(userId: string): Promise<boolean> {
  const { db, battlePassProgressTable } = await import("@workspace/db");
  const { eq } = await import("drizzle-orm");
  const current = currentBattlePassSeason();
  const [row] = await db
    .select({ season: battlePassProgressTable.season })
    .from(battlePassProgressTable)
    .where(eq(battlePassProgressTable.userId, userId))
    .limit(1);
  if (!row) return false; // no progress yet — fresh insert will use the current season
  if (row.season >= current) return false;

  await db
    .update(battlePassProgressTable)
    .set({ season: current, seasonXp: 0, tier: 0, claimedTiers: [], updatedAt: new Date() })
    .where(eq(battlePassProgressTable.userId, userId));
  return true;
}
