/**
 * Admin battle-pass builder: draft → preview → publish → rollback.
 *
 * The battle-pass page has advertised "Admin Builder (draft/preview/publish/
 * rollback)" in a panel that linked to `/admin` — where no such builder existed
 * and no endpoint served one. An admin could not introduce a season at all
 * without hand-writing rows into two tables. That is the gap this closes.
 *
 * The shape follows the product's own rules:
 *
 *   • **Draft** — creating a season writes it with `isActive: false`, so nothing
 *     is live until it is published. A draft can be re-previewed any number of
 *     times; `preview` writes nothing at all.
 *   • **Publish (activate)** — flips one season active and every other season
 *     inactive in a single statement, because two active seasons would make
 *     "which pass am I on" ambiguous at read time.
 *   • **Rollback** — publishing an older season is the rollback; it is the same
 *     operation, so there is no separate code path that can rot.
 *   • **Token-only economy** — tiers carry coins / XP / Focus Tokens / cosmetics.
 *     No real money is involved anywhere in this file, and the purchased-token
 *     rule from `docs/` still governs what tokens can buy.
 *
 * Every write is guarded by `checkAdminAuth` and audited with the admin id, and
 * the tier table is generated by the same pure function the preview shows, so
 * what an admin approves is byte-for-byte what gets published.
 */
import { Router, type Request, type Response } from "express";
import { z } from "zod";
import { db, battlePassRewards, battlePasses } from "@workspace/db";
import { eq, desc, sql } from "drizzle-orm";
import { checkAdminAuth } from "../lib/adminAuth";
import { logger } from "../lib/logger";
import {
  DEFAULT_TIERS,
  MAX_TIERS,
  MIN_TIERS,
  buildSeasonTiers,
  describeReward,
  groupTierRewards,
} from "../lib/battlePassSeasons";
import { sendUnauthorized } from "../lib/httpErrors";

const router = Router();

const seasonIdSchema = z
  .string()
  .trim()
  .min(3)
  .max(40)
  .regex(/^[a-z0-9][a-z0-9-]*$/, "Use lowercase letters, numbers and dashes");

const createSchema = z.object({
  season: seasonIdSchema,
  title: z.string().trim().min(3).max(80),
  /** ISO dates. Defaults to a 30-day season starting today when omitted. */
  startDate: z.string().datetime().optional(),
  endDate: z.string().datetime().optional(),
  tierCount: z.number().int().min(MIN_TIERS).max(MAX_TIERS).default(DEFAULT_TIERS),
  /** Publish immediately. Off by default: a season is a draft until asked for. */
  activate: z.boolean().default(false),
});

const previewSchema = z.object({
  tierCount: z.number().int().min(MIN_TIERS).max(MAX_TIERS).default(DEFAULT_TIERS),
  season: seasonIdSchema.optional(),
});

function defaultWindow(startDate?: string, endDate?: string): { start: Date; end: Date } {
  const start = startDate ? new Date(startDate) : new Date();
  const end = endDate ? new Date(endDate) : new Date(start.getTime() + 30 * 86400000);
  return { start, end };
}

/** What a season looks like to the admin list, without the tier payload. */
async function seasonSummaries() {
  const seasons = await db.select().from(battlePasses).orderBy(desc(battlePasses.createdAt)).limit(50);
  const counts = await db
    .select({ battlePassId: battlePassRewards.battlePassId, tiers: sql<number>`count(distinct ${battlePassRewards.tier})::int` })
    .from(battlePassRewards)
    .groupBy(battlePassRewards.battlePassId);
  const tierCount = new Map(counts.map((row) => [row.battlePassId, row.tiers]));
  return seasons.map((season) => ({
    id: season.id,
    season: season.season,
    title: season.title,
    startDate: season.startDate,
    endDate: season.endDate,
    isActive: season.isActive,
    tierCount: tierCount.get(season.id) ?? 0,
  }));
}

// ── GET /admin/battle-pass — every season, newest first ─────────────────────
router.get("/admin/battle-pass", async (req: Request, res: Response) => {
  if (!(await checkAdminAuth(req))) return sendUnauthorized(res);
  try {
    res.json({ seasons: await seasonSummaries() });
  } catch (err) {
    logger.error({ err }, "admin battle pass list error");
    res.status(500).json({ error: "Could not load seasons" });
  }
});

// ── POST /admin/battle-pass/preview — generate a tier table, write nothing ──
router.post("/admin/battle-pass/preview", async (req: Request, res: Response) => {
  if (!(await checkAdminAuth(req))) return sendUnauthorized(res);
  const parsed = previewSchema.safeParse(req.body ?? {});
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.issues[0]?.message ?? "Invalid preview request" });
    return;
  }
  const tiers = buildSeasonTiers({ tierCount: parsed.data.tierCount, seed: parsed.data.season ?? "preview" });
  res.json({
    tierCount: tiers.length,
    tiers: tiers.map((tier) => ({
      tier: tier.tier,
      xpRequired: tier.requiredXp,
      free: describeReward(tier.free),
      premium: describeReward(tier.premium),
      premiumCosmetic: tier.premium.cosmeticId ?? null,
    })),
  });
});

// ── POST /admin/battle-pass — create a season (draft or published) ──────────
router.post("/admin/battle-pass", async (req: Request, res: Response) => {
  if (!(await checkAdminAuth(req))) return sendUnauthorized(res);
  const parsed = createSchema.safeParse(req.body ?? {});
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.issues[0]?.message ?? "Invalid season" });
    return;
  }
  const { season, title, tierCount, activate } = parsed.data;
  const { start, end } = defaultWindow(parsed.data.startDate, parsed.data.endDate);
  if (end.getTime() <= start.getTime()) {
    res.status(400).json({ error: "The season must end after it starts" });
    return;
  }

  try {
    const [existing] = await db.select({ id: battlePasses.id }).from(battlePasses).where(eq(battlePasses.season, season)).limit(1);
    if (existing) {
      res.status(409).json({ error: `Season “${season}” already exists (${existing.id}). Use a different id.` });
      return;
    }

    const id = `bp_${season}_${Date.now().toString(36)}`;
    const tiers = buildSeasonTiers({ tierCount, seed: season });
    const adminId = typeof (req as Request & { adminId?: string }).adminId === "string" ? (req as Request & { adminId?: string }).adminId : "admin";

    await db.transaction(async (tx) => {
      await tx.insert(battlePasses).values({ id, season, title, startDate: start, endDate: end, isActive: false });
      const rows = tiers.flatMap((tier) => [
        {
          id: `${id}_f_${tier.tier}`,
          battlePassId: id,
          tier: tier.tier,
          type: "coins",
          value: tier.free as unknown as Record<string, unknown>,
          requiredXp: tier.requiredXp,
          isPremium: false,
        },
        {
          id: `${id}_p_${tier.tier}`,
          battlePassId: id,
          tier: tier.tier,
          type: tier.premium.cosmeticId ? "cosmetic" : "tokens",
          value: tier.premium as unknown as Record<string, unknown>,
          requiredXp: tier.requiredXp,
          isPremium: true,
        },
      ]);
      await tx.insert(battlePassRewards).values(rows);
      if (activate) {
        // One statement, so two seasons can never both be active.
        await tx.update(battlePasses).set({ isActive: false }).where(eq(battlePasses.isActive, true));
        await tx.update(battlePasses).set({ isActive: true }).where(eq(battlePasses.id, id));
      }
    });

    logger.info({ id, season, tierCount: tiers.length, activate, adminId }, "battle pass season created");
    res.status(201).json({
      id,
      season,
      title,
      tierCount: tiers.length,
      isActive: activate,
      startDate: start,
      endDate: end,
      tiers: groupTierRewards(tiers.flatMap((tier) => [
        { tier: tier.tier, requiredXp: tier.requiredXp, isPremium: false, value: tier.free },
        { tier: tier.tier, requiredXp: tier.requiredXp, isPremium: true, value: tier.premium },
      ])).map((view) => ({
        tier: view.tier,
        xpRequired: view.xpRequired,
        free: describeReward(view.freeReward),
        premium: describeReward(view.premiumReward),
      })),
      next: activate ? "Live now for every student." : "Draft saved. Publish it when you are ready.",
    });
  } catch (err) {
    logger.error({ err, season }, "admin battle pass create error");
    res.status(500).json({ error: "Could not create the season" });
  }
});

// ── POST /admin/battle-pass/:id/activate — publish, or roll back to ─────────
router.post("/admin/battle-pass/:id/activate", async (req: Request, res: Response) => {
  if (!(await checkAdminAuth(req))) return sendUnauthorized(res);
  const id = String(req.params.id ?? "");
  if (!id) {
    res.status(400).json({ error: "Missing season id" });
    return;
  }
  try {
    const [target] = await db.select().from(battlePasses).where(eq(battlePasses.id, id)).limit(1);
    if (!target) {
      res.status(404).json({ error: "That season does not exist" });
      return;
    }
    await db.transaction(async (tx) => {
      await tx.update(battlePasses).set({ isActive: false }).where(eq(battlePasses.isActive, true));
      await tx.update(battlePasses).set({ isActive: true }).where(eq(battlePasses.id, id));
    });
    logger.info({ id, season: target.season }, "battle pass season activated");
    res.json({ ok: true, id, season: target.season, title: target.title, message: `“${target.title}” is now the live battle pass.` });
  } catch (err) {
    logger.error({ err, id }, "admin battle pass activate error");
    res.status(500).json({ error: "Could not publish that season" });
  }
});

// ── DELETE /admin/battle-pass/:id — remove a draft (never a live season) ────
router.delete("/admin/battle-pass/:id", async (req: Request, res: Response) => {
  if (!(await checkAdminAuth(req))) return sendUnauthorized(res);
  const id = String(req.params.id ?? "");
  try {
    const [target] = await db.select().from(battlePasses).where(eq(battlePasses.id, id)).limit(1);
    if (!target) {
      res.status(404).json({ error: "That season does not exist" });
      return;
    }
    if (target.isActive) {
      // Deleting the live pass would strip every student's progress context;
      // publish another season first, which deactivates this one.
      res.status(409).json({ error: "That season is live. Publish a different season first, then delete this one." });
      return;
    }
    await db.transaction(async (tx) => {
      await tx.delete(battlePassRewards).where(eq(battlePassRewards.battlePassId, id));
      await tx.delete(battlePasses).where(eq(battlePasses.id, id));
    });
    res.json({ ok: true, id });
  } catch (err) {
    logger.error({ err, id }, "admin battle pass delete error");
    res.status(500).json({ error: "Could not delete that draft" });
  }
});

export { router as adminBattlePassRouter };
