import { Router, type IRouter } from "express";
import healthRouter from "./health";
import { authRouter } from "./auth";
import { sessionsRouter } from "./sessions";
import { statsRouter } from "./stats";
import { tasksRouter } from "./tasks";
import { adminRouter } from "./admin";
import { aiRouter } from "./ai";
import { gamificationRouter } from "./gamification";
import { readinessRouter } from "./readiness";
import { coachRouter } from "./coach";
import { focusDnaRouter } from "./focusDna";
import { consequencesRouter } from "./consequences";
import { focusWeatherRouter } from "./focusWeather";
import { roadmapRouter } from "./roadmap";
import { breakFreeRouter } from "./breakFree";
import { siteAnalyticsRouter } from "./siteAnalytics";
import { adminAnalyticsRouter } from "./adminAnalytics";
import { missionsRouter } from "./missions";
import { sitemapRouter } from "./sitemap";
import { socialRouter } from "./social";
import { notificationsRouter } from "./notifications";
import { groupsRouter } from "./groups";
import { retentionRouter } from "./retention";
import { publicProfilesRouter } from "./publicProfiles";
import { aiInsightsRouter } from "./aiInsights";
import { habitsRouter } from "./habits";
import { postsRouter } from "./posts";
import { studyRoomsRouter } from "./studyRooms";
import { dmRouter } from "./dm";
import { shopRouter } from "./shop";
import { goalsRouter } from "./goals";
import { pushRouter } from "./pushSubscriptions";
import { feedbackRouter } from "./feedback";
import { cityRouter } from "./city";
import { lootboxesRouter } from "./lootboxes";
import { questsRouter } from "./quests";
import { dailyRewardRouter } from "./dailyReward";
import { seasonalRouter } from "./seasonal";
import { dreamsRouter } from "./dreams";
import { marketplaceRouter } from "./marketplace";
import { petsRouter } from "./pets";
import { adminCmsRouter } from "./adminCms";
import { premiumRouter } from "./premium";
import { emailRouter } from "./email";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(sessionsRouter);
router.use(statsRouter);
router.use(tasksRouter);
router.use(adminRouter);
router.use(aiRouter);
router.use(gamificationRouter);
router.use(readinessRouter);
router.use(coachRouter);
router.use(focusDnaRouter);
router.use(consequencesRouter);
router.use(focusWeatherRouter);
router.use(roadmapRouter);
router.use(breakFreeRouter);
router.use(siteAnalyticsRouter);
router.use(adminAnalyticsRouter);
router.use(missionsRouter);
router.use(sitemapRouter);
router.use(socialRouter);
router.use(notificationsRouter);
router.use(groupsRouter);
router.use(retentionRouter);
router.use(publicProfilesRouter);
router.use(aiInsightsRouter);
router.use(habitsRouter);
router.use(postsRouter);
router.use(studyRoomsRouter);
router.use(dmRouter);
router.use(shopRouter);
router.use(goalsRouter);
router.use(pushRouter);
router.use(feedbackRouter);
router.use(cityRouter);
router.use(lootboxesRouter);
router.use(questsRouter);
router.use(dailyRewardRouter);
router.use(seasonalRouter);
router.use(dreamsRouter);
router.use(marketplaceRouter);
router.use(petsRouter);
router.use(adminCmsRouter);
router.use(premiumRouter);
router.use(emailRouter);

export default router;
