import { Router, type IRouter } from "express";
import healthRouter from "./health";
import { authRouter } from "./auth";
import { sessionsRouter } from "./sessions";
import { statsRouter } from "./stats";
import { tasksRouter } from "./tasks";
import { adminRouter } from "./admin";
import { aiRouter } from "./ai";
import { gamificationRouter } from "./gamification";
import { readinessRouter } from "./readiness";
import { distractionsRouter } from "./distractions";
import { profilesRouter } from "./profiles";
import { coachRouter } from "./coach";
import { focusDnaRouter } from "./focusDna";
import { ghostsRouter } from "./ghosts";
import { consequencesRouter } from "./consequences";
import { focusWeatherRouter } from "./focusWeather";
import { sessionReplayRouter } from "./sessionReplay";
import { roadmapRouter } from "./roadmap";
import { breakFreeRouter } from "./breakFree";
import { siteAnalyticsRouter } from "./siteAnalytics";
import { adminAnalyticsRouter } from "./adminAnalytics";
import { missionsRouter } from "./missions";
import { sitemapRouter } from "./sitemap";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(sessionsRouter);
router.use(statsRouter);
router.use(tasksRouter);
router.use(adminRouter);
router.use(aiRouter);
router.use(gamificationRouter);
router.use(readinessRouter);
router.use(distractionsRouter);
router.use(profilesRouter);
router.use(coachRouter);
router.use(focusDnaRouter);
router.use(ghostsRouter);
router.use(consequencesRouter);
router.use(focusWeatherRouter);
router.use(sessionReplayRouter);
router.use(roadmapRouter);
router.use(breakFreeRouter);
router.use(siteAnalyticsRouter);
router.use(adminAnalyticsRouter);
router.use(missionsRouter);
router.use(sitemapRouter);

export default router;
