import { Router, type IRouter } from "express";
import healthRouter from "./health";
import { authRouter } from "./auth";
import { sessionsRouter } from "./sessions";
import { statsRouter } from "./stats";
import { tasksRouter } from "./tasks";
import { adminRouter } from "./admin";
import { aiRouter } from "./ai";
import { gamificationRouter } from "./gamification";
import { readinessRouter } from "./readiness";
import { distractionsRouter } from "./distractions";
import { profilesRouter } from "./profiles";
import { coachRouter } from "./coach";
import { focusDnaRouter } from "./focusDna";
import { ghostsRouter } from "./ghosts";
import { consequencesRouter } from "./consequences";
import { focusWeatherRouter } from "./focusWeather";
import { sessionReplayRouter } from "./sessionReplay";
import { roadmapRouter } from "./roadmap";
import { breakFreeRouter } from "./breakFree";
import { siteAnalyticsRouter } from "./siteAnalytics";
import { adminAnalyticsRouter } from "./adminAnalytics";
import { missionsRouter } from "./missions";
import { sitemapRouter } from "./sitemap";
import { socialRouter } from "./social";
import { notificationsRouter } from "./notifications";
import { groupsRouter } from "./groups";
import { retentionRouter } from "./retention";
import { publicProfilesRouter } from "./publicProfiles";
import { aiInsightsRouter } from "./aiInsights";
import { habitsRouter } from "./habits";
import { postsRouter } from "./posts";
import { studyRoomsRouter } from "./studyRooms";
import { dmRouter } from "./dm";
import { shopRouter } from "./shop";
import { goalsRouter } from "./goals";
import { pushRouter } from "./pushSubscriptions";
import { feedbackRouter } from "./feedback";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(sessionsRouter);
router.use(statsRouter);
router.use(tasksRouter);
router.use(adminRouter);
router.use(aiRouter);
router.use(gamificationRouter);
router.use(readinessRouter);
router.use(distractionsRouter);
router.use(profilesRouter);
router.use(coachRouter);
router.use(focusDnaRouter);
router.use(ghostsRouter);
router.use(consequencesRouter);
router.use(focusWeatherRouter);
router.use(sessionReplayRouter);
router.use(roadmapRouter);
router.use(breakFreeRouter);
router.use(siteAnalyticsRouter);
router.use(adminAnalyticsRouter);
router.use(missionsRouter);
router.use(sitemapRouter);
router.use(socialRouter);
router.use(notificationsRouter);
router.use(groupsRouter);
router.use(retentionRouter);
router.use(publicProfilesRouter);
router.use(aiInsightsRouter);
router.use(habitsRouter);
router.use(postsRouter);
router.use(studyRoomsRouter);
router.use(dmRouter);
router.use(shopRouter);
router.use(goalsRouter);
router.use(pushRouter);
router.use(feedbackRouter);

export default router;
